version: '3.9'

services:
  db:
    image: postgres:14.2
    container_name: postgres14
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
