version: '3.9'
services:
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=password
      - REDIS_TLS_ENABLED=no
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/data:/bitnami/redis/data

